### ISSUE TITLE
Stock config seems broken

### ISSUE THREAD

**Issue by danielbene** [open-eats/OpenEats#104]
It took me some time to figure this out, so I tought I might share it, despite of the seemingly inactive maintenance.

**TL;DR: the stock usage of the mariadb latest tag broken (possibly the app incompatible with the 10+ versions). By using the 5.5.64 tag inside the docker_prod.yml, everything seems working.**

If you experience mysql error:11, or see no created openeats database inside the container's mysql, after the quick_start script, than it may fix the problem.

**Comment by lw1959** [comment]
Thank you for the comment, using the 5.5.64 tag solved my issue as well in a new install

**Comment by RyanNoelk** [comment]
Thanks for commenting I'll add a fix for this.

**Comment by RyanNoelk** [comment]
I have updated the image tag to 5.5.64. I will dig into this deeper later on .

**Comment by danielbene** [comment]
Nice, thank you 🙂
