### ISSUE TITLE
How do you add a recipe to a grocery list?

### ISSUE THREAD

**Issue by toddobryan** [open-eats/OpenEats#106]
It looks like you can do this based on another issue question, but I can't figure out how.

Is this possible?

**Comment by toddobryan** [comment]
Never mind. I just found it. There's a button under the ingredients. I think you have to have created a grocery list first, but once you have, you can add a whole recipe to that list.

I'll leave this here for people who may search like I did.

**Comment by BryceStevenWilley** [comment]
Also going to note for others: you have to check the ingredients you want to add to the list from the recipe you are on, either by individual checking them, or clicking the "Check all" button.
