### ISSUE TITLE
Taking a complete backup of the solution

### ISSUE THREAD

**Issue by lavacaquerie** [open-eats/OpenEats#120]
Hi!
I'd like to ask how should i take a complete backup of the solution. I mean SQL dump and images. And of course, how to restore it.

Recently I panic during a few moments so I'd like to know hoy tu backup my recipes that worth to me thousands of hours.

**Comment by danielbene** [comment]
@lavacaquerie Hi there! I wrote a manual backup/restore script for one of my project. With some modification it can be used for your setup, or at least give you an idea how to create one. You can find them [here](https://github.com/danielbene/server-terraformer/tree/master/backup), if you interested.

**Comment by RyanNoelk** [comment]
[See the docs](https://github.com/open-eats/OpenEats/blob/master/docs/Taking_and_Restoring_Backups.md)
