### ISSUE TITLE
Feature Request: Docker Image for ARM

### ISSUE THREAD

**Issue by Slinky-Wrangle-Punch** [open-eats/OpenEats#123]
It would be nice to have an ARM docker image for easy deployment on the raspberry pi.

**Comment by RyanNoelk** [comment]
I really don't think this is going to happen any time soon. 

I would add a link in the docs if someone decides to support this type of docker image.

**Comment by Slinky-Wrangle-Punch** [comment]
I forked the repos and implemented the ARM docker support. The changes are really small. Mostly I just had to use newer base images in the Dockerfile. The new base images already support ARM and then the OpenEats Dockerfiles build smoothly. 

I pushed the new ARM docker images to docker-hub. So the quick-start.py in my fork uses them directly and it behaves exactly like the main repo.

If you update the base images of the Dockerfiles, the ARM support could be easily implemented.

Some links for easy access:
https://github.com/atroxtartarus/OpenEats
https://github.com/atroxtartarus/openeats-api
https://github.com/atroxtartarus/openeats-nginx
https://github.com/atroxtartarus/openeats-web

https://hub.docker.com/r/atroxtartarus/openeats-api
https://hub.docker.com/r/atroxtartarus/openeats-nginx
https://hub.docker.com/r/atroxtartarus/openeats-web

**Comment by RyanNoelk** [comment]
If the changes are small, feel free to open a PR and I can take a look. 

Otherwise I'll add likes to your repo in the docs here for those looking for ARM support.

Thanks 👍
