### ISSUE TITLE
Feature Request: Sections

### ISSUE THREAD

**Issue by jachin** [open-eats/OpenEats#125]
In the directions it would be great to another formatting option (other than list of direction). Being able to specify sections. For instance I'm adding a recipe for fried chicken and it would be great to call out different sections like: "The Night Before", "Friend Chicken", "Spicy Oil".

I used to use Pepper plate and you could format the sections like so.

```
[The Night Before]
Cut up and debone chicken
Season chicken generously with salt
[The Chicken]
In one bowl whisk together eggs, buttermilk and hot sauce
In another bowl whisk the flour, 2 pinches of salt
Place dutch oven over medium heat.
Add oil to a depth of 1.5 inches 
Heat oil to 360F
Dredge the chicken (dry, wet, dry)
Cook chicken in the oil for about 12 minutes (9 for smaller pieces, 16 for larger pieces)
Let cool on a wire rack set over a baking sheet
[Spicy Oil]
Combine the cayenne pepper, brown sugar, paprika, cumin, and galric in a small bowl.
Add 0.25 cups of oil.
Brush the chicken with the spicy oil.
```

Having sections in the ingredients would also be great.

**Comment by hertfelder** [comment]
If you add a colon (`:`) at the end of the line with the section name, it gets rendered in bold face and not as a list item. Maybe that is already sufficient for your use case.

**Comment by jachin** [comment]
Oh yeah, that's exactly what I need. Thanks so much.
