### ISSUE TITLE
German languages will not be displayed.

### ISSUE THREAD

**Issue by TheTwist-76** [open-eats/OpenEats#134]
I use OpenEats in the Docker Container. 
I want to use it in German. So I have set the following variable:  NODE_LOCALE=de
When I login with the console of the container and type "env" NODE_LOCALE=de is set. 
However, only the English language is displayed. 

Even if I rename the language files in the directory de.json to en.json only English is displayed. What am I doing wrong?

**Comment by RyanNoelk** [comment]
When you update the `NODE_LOCALE` in the env file do you restart the containers as well? For the locale settings to be applied you should run the restart script: `quick-start.py`

**Comment by jzyrobert** [comment]
Do you simply have to restart the containers or rebuild them?
As I understand it, the environment variables are copied during the build process by webpack?

**Comment by geekblog-dev** [comment]
I have exactly the same Problem figured out there is no quick-start.py but there is a gunicorn_start.sh

**Comment by geekblog-dev** [comment]
Using the Docker from https://github.com/MrNuggelz/OpenEats
find / -name quick-start.py ends up with no result.

**Comment by RyanNoelk** [comment]
Updating [NODE_LOCALE ](https://github.com/open-eats/OpenEats/blob/master/docs/samples/sample_env_file.list#L18)=de in your env file and then restarting the containers will update the i18n files and will display the site in German. Running the `quick-start.py` will restart the containers for you. options for supported langs can be found [here](https://github.com/open-eats/OpenEats/blob/master/docs/Setting_up_env_file.md#node_locale) 

> I have exactly the same Problem figured out there is no quick-start.py but there is a gunicorn_start.sh
> Using the Docker from https://github.com/MrNuggelz/OpenEats
> find / -name quick-start.py ends up with no result.

If you are having trouble with that fork please open a ticket in that repo, not here.
