### ISSUE TITLE
Licensing GPLv2 <> MIT

### ISSUE THREAD

**Issue by FAUSheppy** [open-eats/OpenEats#135]
How comes this repository is licensed MIT when the original project was licensed GPL?
As far as I understand it, this:

https://sourceforge.net/projects/openeats/

is the original project, which is also hosted here:

https://github.com/qgriffith/OpenEats

Is your project not a fork? If no it would be great to clarify this in the README (since it has the same name), if yes, did you get permission by the owner to relicense his work? It's not that I personally care, but you are potentially screwing over other people and yourself if someone ever sells this software and doesn't distribute the code as would be required by GPLv2.

GPLv2 is not a big deal for web-applications. If this is a fork of the original openeats the license of this project should be changed and it should be clarified in the license file that the MIT-license was a mistake and was never valid in the first place. GPLv2 also has a clause which allows it to be relicensed as any late version, so you could even make it GPLv3.

**Comment by RyanNoelk** [comment]
I'm not going to claim I am a legal expert and maybe you have a lot more experience then me in this. So please correct me if you think I an wrong in any of the points below.

The original OpenEats project you (as linked via github) doesn't not contain any reference to GPL. The only reference (outside of 3rd party package) the code makes to licensing is in the [__init__.py file](https://github.com/qgriffith/OpenEats/blob/master/__init__.py#L3). For additional reference, [here is the last commit by the original author that I forked](https://github.com/RyanNoelk/OpenEats/blob/9373ce65f838f19fead6f73c9491d2211e770769/__init__.py#L3). There, it references a BSD license. It doesn't contain any description of the terms or which BSD license, So I assumed [Zero Clause BSD](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22Zero_Clause_BSD%22))

I'm not sure why sourceforge has a different license then the source code. TBH I didn't even know this code was hosted there.

In any case, PRs are welcome if you the license should be changed.

**Comment by FAUSheppy** [comment]
No, everything is fine then. It's unfortunate he only set it in the init-file, making it somewhat hard to find, but it should be sufficient. I'm going to close this, if anybody wonders about this again he will find this Issue.
