### ISSUE TITLE
Create sections of ingredients for multi-part recipes

### ISSUE THREAD

**Issue by dlchamp** [open-eats/OpenEats#153]
Would it be possible to have the ingredients lists broken into sections?  Some recipes have multiple pieces made/prepared separately before being combined into the final product.       
  
Maybe some kind of tag to identify the line as a heading instead of an item on the list.  Like, ~~ or **.
  
 For example, cookies with icing.

**For the Cookies**
- item 1  
- item 2
- ....

**For the Icing**
- item 1
- item 2
- ...

**Comment by Drudoo** [comment]
This is actually possible. Try like this:

```
For the Cookies:
item 1
item 2
For the Icing:
item 1
item 2
```

It works in both Ingredients and Directions but you have to use a `:` and no additional newline afterwards.

**Comment by dlchamp** [comment]
Well, then... That's amazing!   Thanks


Is there anywhere with actual documentation on how to use openeats?   It's pretty straight forward but I may have found that out without having to ask here.   And Google has provided no results

**Comment by Drudoo** [comment]
@dlchamp There really isn't. I found this by accident just by trying. It is frustrating how little usage documentation there's available.

**Comment by dlchamp** [comment]
Yeah, I tried a couple different things, using : just didn't cross my mind.   Thanks for the help

**Comment by rustymyers** [comment]
Working on adding some docs. https://github.com/open-eats/OpenEats/pull/154
