### ISSUE TITLE
Running OpenEats without Docker

### ISSUE THREAD

**Issue by RyanNoelk** [open-eats/OpenEats#31]
We should have a way to run OpenEats without docker. The following needs to be done in order for this to work.

- [x] Adding non-docker support to openeats-web. 
- [x] Add documentation on how to setup openeats-web outside of docker.
- [x] Adding non-docker support to openeats-api.
- [x] Add documentation on how to setup openeats-api outside of docker.
- [x] Because custom settings are stored in env files we need to make them available from a settings files for both openeats-api and openeats-web
- [x] Add general documentation and an example of how an nginx configure would work
- [x] Add general documentation oh how all the services are linked together.
- [x] Help from others willing to test!

**Comment by zingz0r** [comment]
Hi, I managed to run openeats without docker on debian. I wrote a how-to on my wiki: https://wiki.tothnet.hu/index.php/Install_OpenEats_without_Docker_and_run_on_Apache2
Maybe this will help.

**Comment by RyanNoelk** [comment]
That looks awesome! I'll check if out this weekend. Do you mind If I place a link to this inside the OpenEats docs?

**Comment by zingz0r** [comment]
Feel free to add the link or the content to your docs.  If I forgot something from the wiki or it's not working 
for some reason, don't hesitate to ask me about it.

**Comment by RyanNoelk** [comment]
Overall this works great! See below for my thoughts:
- pip packages should be installed in a virtual env - [see here](https://packaging.python.org/guides/installing-using-pip-and-virtualenv/)
- mysql-config wasn't found by default, it needs another packge - `apt-get install libmysqlclient-dev`
- env vars - OpenEats-web only needs to have access to the `NODE_` env vars and the API needs access to the others.


api:
```
# Database config
MYSQL_HOST=localhost
MYSQL_DATABASE=openeats
MYSQL_USER=username
MYSQL_ROOT_PASSWORD=password

# Django config
API_URL=0.0.0.0:5210
API_PORT=5210
DJANGO_SECRET_KEY=CHANGE_THIS:SECRETKEY
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=openeats.domain.com  # if you running from a domain you have to specify the hostname here [default value was localhost]

# If you are serving content behind an HTTPS proxy,
# Set this to `true`.
# See: https://docs.djangoproject.com/en/1.10/ref/settings/#secure-proxy-ssl-header
HTTP_X_FORWARDED_PROTO=true  # We are using ssl maybe you need to change it back to false
```

web:
```
export NODE_ENV=development
export NODE_URL=openeats.domain.com:5200 # As far as I tested the port can be anything here we wont use it
export NODE_API_URL=https://openeats.domain.com  # the openeats domain with http or https
export NODE_LOCALE=en
```


I you have the time and are willing, I would love a pull request with the docs in markdown. It would go in the docs folder and have a link on the main README. Otherwise, I will work on getting this into the project repo by next week :)

**Comment by davekaufman** [comment]
I was able to follow the above instructions / wiki link and successfully get openeats running on ubuntu without docker.  I did have to edit one additional file:  in the `openeats-api` repo, I had to edit  `base/settings.py`  lines 221 and 222 `MEDIA_URL` and `STATIC_URL`   and prepend my domain url in order to get recipe images to load successfully. (Prior to the edit, I could add an image to a recipe successfully, but not view it, as the image url would be `http://localhost:5210/site-media/upload/recipe_photos/IMAGE_NAME.jpg` instead of the correct `http://openeats.example.com/site-media/upload/recipe_photos/IMAGE_NAME.jpg`

```diff
--- settings.py.orig	2018-07-27 15:54:11.510476493 -0700
+++ settings.py	2018-07-27 15:54:26.146829183 -0700
@@ -216,8 +216,10 @@
 # URL that handles the media served from MEDIA_ROOT. Make sure to use a
 # trailing slash if there is a path component (optional in other cases).
 # Examples: "http://media.lawrence.com", "http://example.com/media/"
-MEDIA_URL = '/site-media/'
-STATIC_URL = '/static-files/'
+MEDIA_URL = 'http://openeats.example.com/site-media/'
+STATIC_URL = 'http://openeats.example.com/static-files/'
```

**Comment by RyanNoelk** [comment]
That will be dependent on your proxy server setup IE: Apache or Nginx should be handling this. This is documented with in the Wiki under `/etc/apache2/sites-available/default.conf`

For Nginx See:
https://github.com/open-eats/openeats-nginx/blob/master/default.conf#L38

For Apache See:
```
       Alias /static-files /opt/openeats/openeats-apache2/static-files
       <Directory "/opt/openeats/openeats-apache2/static-files">
           Options Indexes FollowSymLinks MultiViews
           AllowOverride All
           Order allow,deny
           allow from all
           Require all granted
       </Directory>
       Alias /site-media /opt/openeats/openeats-apache2/site-media
       <Directory "/opt/openeats/openeats-apache2/site-media">
           Options Indexes FollowSymLinks MultiViews
           AllowOverride All
           Order allow,deny
           allow from all
           Require all granted
       </Directory>
```

**Comment by RyanNoelk** [comment]
See: #44
