### ISSUE TITLE
404 at account settings

### ISSUE THREAD

**Issue by MrNuggelz** [open-eats/OpenEats#32]
I created a super user and was able to log in, but when i try to access "My account" i get a 404 error. The requests to /admin/ and bundle.js are fine but for some reason the bundle.js seems to produce the 404 error.

**Comment by RyanNoelk** [comment]
I'll take a look into this. Looks like a bad nginx proxy config.

**Comment by MrNuggelz** [comment]
Thanks for the fast reply.
I use jwilder/nginx-proxy as the nginx proxy. If it's any help, i've attached the [docker-compose.yml](https://github.com/open-eats/OpenEats/files/1902264/docker-compose.txt) i'm using. The env_prod.list is the same as [sample_env_file.list](https://github.com/open-eats/OpenEats/blob/master/docs/samples/sample_env_file.list).

**Comment by RyanNoelk** [comment]
Ahh ok. I see that you are using your own nginx proxy. OpenEats comes with it's own nginx proxy to link all the services. If you want to use your own, just make sure that you take a look at the following, https://github.com/open-eats/openeats-nginx/blob/master/default.conf.


Looks like you are just missing the admin redirect, See: https://github.com/open-eats/openeats-nginx/blob/master/default.conf#L33-L36. Just make sure that you redirect all calls to `/admin` to the API.

**Comment by RyanNoelk** [comment]
Still having issues or can I close this?

**Comment by MrNuggelz** [comment]
Redirecting /admin to the API didn't work, cause nginx-proxy resolved the domain name to the IP and the API does only respond to the domain. Now i moved bach to openeats-nginx running on a different port.
