### ISSUE TITLE
Issue: Recipe with parenthesis in the name has bug in Browse Recipe Page

### ISSUE THREAD

**Issue by cearum** [open-eats/OpenEats#38]
[Edit] After some more playing it seems the issue might be with recipes that don't have an image.

If a recipe has a parenthesis in the name it creates a bug in the browse recipe page making an incomplete line of recipes (See Image below). 

Removing the parenthesis from title in the editor doesn't seem to recover from the issue. It takes deleting the recipe and recreating without the parenthesis to recover from the issue.

Server:
I'm working on what should be latest Docker Image (Installed this past weekend 5/26/18)
Linux mint 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 
Browsing Computer:
Google Chrome: Version 66.0.3359.181 (Official Build) (64-bit)
Windows 10 Pro Version 1803

![image](https://user-images.githubusercontent.com/33786368/40665068-56d7f8b6-632a-11e8-9f6b-671fae5b388b.png)

**Comment by RyanNoelk** [comment]
Hey there,

Sorry for the late reply, been pretty busy lately. Anyways, I wasn't able to reproduce the error with the parenthesis but there is some weird behaviors that I haven't gotten around to fixing.
- The browse pages are cached and they are not busted until you reload the page (with either F5 or clt/cmd + R). This means that if you create a recipe you won't see it until you refresh. See: (https://github.com/open-eats/OpenEats/issues/39)
- If a recipe doesn't have an image, a default one is provide. Sometimes there is some weirdness with the sizing of a default image causing the layout to break. I thought I had fix this issue but after looking at your screenshot I don't think I have. See: (https://github.com/open-eats/OpenEats/issues/40)

I created two separate issues that once I have some more free time (a couple weeks) I will get fixed up.

cheers!

**Comment by RyanNoelk** [comment]
I have corrected the issues that I have mentioned above. Please let me know if you are still having issues.
