### ISSUE TITLE
Returning to the Create tab retains information from old recipe

### ISSUE THREAD

**Issue by Jemikwa** [open-eats/OpenEats#43]
Issue: When I create a recipe and successfully submit it to the site, returning to the Create tab retains the information I filled out in each field. If I delete this text and try to input a new recipe, the page gives the error "Recipe failed to save. Please try again." with no indication on if a field was incorrectly filled out or otherwise.

How to replicate:
-Create recipe and click Submit recipe to successfully save to the site.
-Click on the Create tab at the top.
-Notice information from the recipe is still present. 
![image](https://user-images.githubusercontent.com/5904385/43347072-75a472de-91b9-11e8-9334-c681e5e781d4.png)
-Delete the information in each field and reinput new information (I've done this where only one field is edited, and where all fields are changed, with no change in behavior). Click Save or Submit and the page produces "Recipe failed to save. Please try again." at the top.
![image](https://user-images.githubusercontent.com/5904385/43347168-da193222-91b9-11e8-9a35-7d8c0dc2891d.png)
-New recipe does not save in any manner, and the page has to be refreshed to clear out every field and be able to successfully submit new recipes.

My more programming savvy SO provided me with this information:

> When creating the first recipe, it sends a POST request to  https://eats.example.com/api/v1/recipe/recipes/
> When creating the second recipe, it sends a PATCH request to  https://eats.example.com/api/v1/recipe/recipes//
> (extra trailing slash)
> Simply changing the PATCH to a POST works.
> When updating an existing recipe, the request looks like this:
> PATCH https://eats.example.com/api/v1/recipe/recipes/yum-yums/
> The frontend thinks you're editing an existing recipe on the create form. When it tries to submit this new recipe as an edit, it has nothing for the URL name, so that's why you get the double slashes.

I hope this helps!

**Comment by RyanNoelk** [comment]
Nice catch! Looks like the cache is thinking you are trying to edit the same recipe you just created, rather than create a new one.

For a quick fix, you should be able to just refresh the page and everything should be working fine. 

I'll dig into the code and find a fix for this issue.

**Comment by RyanNoelk** [comment]
This should be fixed in the master/latest version. The recipe form will be wiped when you create a new recipe. If you edit a recipe and then leave the recipe creation page. You will still be able to go back and see the changes.
