### ISSUE TITLE
Error during net-new Docker & OpenEats Install:  MariaDB "Access denied for user 'root'@'localhost'"

### ISSUE THREAD

**Issue by jnikolich** [open-eats/OpenEats#47]
## Environmental Details
- Host Environment: **VMWare ESXi 6.7** (fresh VM)
- Host O/S: **Fedora 28 64-bit** (freshly-installed OS)
- Docker Version:  **docker-ce-18.06.1.ce-3.fc28**
- Docker Compose Version:  **1.22.0**

## Problem Description
Hello there.  I am in the process of installing OpenEats into a net-new Docker host. _I.e._ I first installed Docker in a fresh VM, got it up and running, and then installed [Portainer](https://portainer.io/) before proceeding directly to the [OpenEats install guide](https://github.com/open-eats/OpenEats/blob/master/docs/Running_the_App.md).  No other images/containers were installed prior, with the exception of Portainer.

The installs of Fedora, Docker, Portainer and OpenEats appeared to all complete without error.  For OpenEats, I completed all steps up to and including adding course/cuisine data in **First Time Setup**.

When I then try hitting the web UI, I get a blank screen.  I noticed the following errors in the _**openeats_db-1**_ logs (this appears after what looks like a normal initialization):
````
2018-08-22 23:48:28 8 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
````
I then manually verified the issue by consoling into **openeats_db_1** and running the following (testing root login with & without supplied password):
````
root@777d0228231b:/# mysql -u root
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
root@777d0228231b:/# mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 58
Server version: 10.3.9-MariaDB-1:10.3.9+maria~bionic mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
````
## Workaround
To work around this, I created `~root/.my.cnf` (perms 0600) with the following content:
````
[client]
user=root
password=root
host=localhost
````
... wherein the specified password corresponds what I believe the default for OpenEats is.  When I re-ran the `quick-start.py` script, this time I was able to hit the login page for OpenEats.
## Questions
1. Is it possible I misconfigured something when installing OpenEats?  (See my config below)
2. Or, is there an expectation that a MariaDB container already exists, has been configured, and runs correctly? 
In both of these cases, I suspect a simple documentation change might suffice to rectify.

Thank you very much for a very useful recipe app!
### env_prod.list
````# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=kshadkhskjSECRET-KEYkdjfsfkhk3h4hsdd
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=docker.<example.com>
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_API_URL=http://docker.<example.com>/
NODE_LOCALE=en
````
### docker-prod.override.yml
````
version: '2.3'
services:
  nginx:
    ports:
        - "8000:80"
````

**Comment by RyanNoelk** [comment]
Hi,

Thanks for the detailed report. I will try and replicate the issue. However I'm not sure if this was caused by the DB. Regardless of if the DB/API were working or not, the UI should load (you just won't get any content). 

If you were getting a blank screen when trying to load the App in a web browse, then there was something funky going on with the UI. One potential cause of this could be the extra time that the UI needs on a first time boot to load all the NPM packages. After the first boot the UI caches all the NPM packages so you don't need to install them again.

Back to the DB issues. The Postgres container will use the settings you have in the `env_prod.list
` file to initialize itself. So if these values weren't initialize, the API uses the defaults: https://github.com/open-eats/openeats-api/blob/master/base/settings.py#L28-L32

Couple closing questions for you:
- Is the App working as expected now: IE you can use it.
- Are you trying to re-use another dockerized DB container (outside of the one that OpenEats will create)?

-Ryan

**Comment by jnikolich** [comment]
To answer your closing questions first:
1. _"Is the App working as expected now: IE you can use it"_.  **No, however I now believe this to be unrelated to this problem-report (see below).**
1. _"Are you trying to re-use another dockerized DB container?"_.  **No, the only DB involved is the one created during OpenEats' installation.  This also includes no external (non-dockerized) DB instances.**

During my previous installation attempt, I waited approx. 30 secs before hitting the main page (I think I read about 30 secs somewhere in the doc'n).  This time, to try and confirm your first-time-boot suspicion, I blew away all OpenEats containers, images, volumes and networks, and did a full reinstall from scratch, waiting 5 minutes after `quick-start.py` completed before hitting the main page.  As you suspected, this time the main page got successfully (sort of) served up.

So it looks like, although no-password warnings are still being thrown, this does not appear to be inhibiting presentation of the homepage after initial installation.  Whether or not those no-password warnings allude to future problems I cannot say, since I cannot yet fully utilize the app properly.

## Unrelated Issues
The app still does not function correctly.  However I suspect this to be caused by my use of an external (non-dockerized) Apache reverse-proxy (for HTTPS), combined with OpenEats apparently serving up static-content URLs.  I will troubleshoot this separately, as I believe it's unrelated to this problem report. (Hopefully it's mis-configuration on my part.)

Thanks again for your quick response and sorry for the red-herring.

**Comment by RyanNoelk** [comment]
Good to know that was the issue. I'll be sure to update the docs to add that warning in there.

As for the HTTPS issues, you might wanna checkout this issue: https://github.com/open-eats/openeats-api/issues/15
