### ISSUE TITLE
[Feature Request] I would like to be able to input Direction Groups

### ISSUE THREAD

**Issue by renatolond** [open-eats/OpenEats#49]
When creating recipes, the ingredients can be grouped (for instance: dough and icing), but the same doesn't seem possible for directions (but it's quite useful, specially for desserts).

**Comment by RyanNoelk** [comment]
Makes since. An idea how you would want this to look? Or should it be similar to the ingredients. 

Most recipes I use have a start to finish order. IE, you do one thing at a time then move on to the next. An example of why you need this order would also help.

**Comment by renatolond** [comment]
For me just like the ingredients, indeed :)

An example is this one: https://www.willcookforsmiles.com/avocado-salmon-rice-bowl/
The recipe has three components. They can be made at any order, so it's really good to see them as groups.

**Comment by rustymyers** [comment]
I'd like to +1 this request, but also offer my process as a workaround. The linked recipe for avocado salmon rice bowl technically contains three recipes. Each recipe creates one of the three main components to the dish. In order for the ingredients and directions to be "categorized" in to the main components, I would create three recipes with a reference to each one. This obviously is less than idea, as you're having to pull up multiple pages for a single meal, but with sides, condiments, mains, and deserts all in separate recipes, you have to do that anyway.

To be clear, I don't think my workaround is idea. I'd rather have the requested grouping described herein. Just sharing how I do it.

**Comment by renatolond** [comment]
I have that for recipes that use bechamel sauce, for instance. Since Bechamel is used in so many recipes, it makes sense to have it as a separate component, but not always the components on themselves make sense as a full separate recipe, I think. But indeed, it's a workaround.

**Comment by RyanNoelk** [comment]
Give this branch A try and see if it works as you would expect.

https://github.com/open-eats/openeats-web/pull/19

**Comment by renatolond** [comment]
Perfect :ok_hand:

**Comment by RyanNoelk** [comment]
Added in https://github.com/open-eats/openeats-web/pull/19
