### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by renatolond** [open-eats/OpenEats#50]
I created an openeats instance for close family, but I don't know exactly how to give them access. I created a test user and I have to input a password at that point. If I login with that user, which is a common user, they cannot change their own password (I get a `Please enter the correct username and password for a staff account.` error if I try the /admin/ path)
I don't see any way of sending recovery passwords email either, so that's also not an option.
Is there a way to change/recover password at the moment?

**Comment by RyanNoelk** [comment]
No, not at the moment :/ 

I personally haven't had the need for it, but it's always been in the back of my mind. I want to build out a django style, user settings page in react (https://github.com/open-eats/OpenEats/issues/7). This will let the user change there password. Sending emails is a bit of a PITA, so I probably won't ever have a reset password functionality in that way.

For now they just have to be happy with give you the password they want to use. PRs Welcome !

**Comment by RyanNoelk** [comment]
Closing this issue and adding it to #7
