### ISSUE TITLE
List: Breakpoint for buttons on small devices

### ISSUE THREAD

**Issue by romankh** [open-eats/OpenEats#52]
Hi, 

on small devices, the buttons below the grocery list overlap as it can be seen in the screenshot.
Best way to fix this would probably be to display the label, the filters and the completed button stacked underneath the other, when a certain breakpoint is reached

![openeats-1](https://user-images.githubusercontent.com/1597874/45501759-6d2b8400-b782-11e8-9bc2-076e3a6570e8.png)

**Comment by RyanNoelk** [comment]
I've always been too lazy to fix them cause in English they don't look too bad :P 

I'll most likely change the delete button to an icon then remove all text that comes with the items remaining.

**Comment by RyanNoelk** [comment]
See: https://github.com/open-eats/openeats-web/pull/20 for a fix

**Comment by romankh** [comment]
Thanks a lot, looks much better now
