### ISSUE TITLE
Sharing grocery list is not working

### ISSUE THREAD

**Issue by romankh** [open-eats/OpenEats#53]
Should shared grocery lists work already ? 
I tried sharing a grocery list with a second user (in django management area), but it resulted in an error (with an underlying http 500 response). 
Also tried adding an entry into table list_groceryshared directly, but it had no effect

**Comment by RyanNoelk** [comment]
I haven't implemented them yet. But what I can do is implement the changes on the backend so you can control access via the Django admin interface.

**Comment by RyanNoelk** [comment]
I added support for for sharing lists via the admin panel in this PR: https://github.com/open-eats/openeats-api/pull/18. You should be able to use it now without issue.

**Comment by romankh** [comment]
Thank you very much again, it's working now.
