### ISSUE TITLE
Recipe Course/Cuisine/Rating Doesn't Show up in Filters on Browse Screen until Refresh

### ISSUE THREAD

**Issue by cearum** [open-eats/OpenEats#56]
It's a small bug, but after adding a recipe to a previously empty course (e.g. Breakfast) that course doesn't show up in the Filters on the Browse Screen until the user manually refreshes the page (F5 or otherwise). 

Same thing for a cuisine and ratings.

(I'm just adding a bunch of recipes and none of the new courses showed up in the filters until I refreshed)

**Comment by RyanNoelk** [comment]
👍 

I'm going to be reworking the Course/Cuisine stuff in an upcoming patch. I will be sure to include a fix to this then.

**Comment by RyanNoelk** [comment]
I update the way Courses/Cuisines are handled. This should be resolved.
