### ISSUE TITLE
Question about OpenEats Docker

### ISSUE THREAD

**Issue by SirTerrific** [open-eats/OpenEats#59]
Hi,

I try to use Openeats but when I start all my dockers, I have this message. I don't know if it is normal or not.

web_1    | Compiled successfully.
web_1    | 
web_1    | File sizes after gzip:
web_1    | 
web_1    |   264.98 KB (-5 B)  build/static/js/main.cd245a94.js
web_1    |   5.79 KB           build/static/css/main.8d187868.css
web_1    | 
web_1    | The project was built assuming it is hosted at the server root.
web_1    | You can control this with the homepage field in your package.json.
web_1    | For example, add this to build it for GitHub Pages:
web_1    | 
web_1    |   "homepage" : "http://myname.github.io/myapp",
web_1    | 
web_1    | The build folder is ready to be deployed.
web_1    | You may serve it with a static server:
web_1    | 
web_1    |   yarn global add serve
web_1    |   serve -s build
web_1    | 
web_1    | Find out more about deployment here:
web_1    | 
web_1    |   http://bit.ly/2vY88Kr
web_1    | 
web_1    | Done in 25.58s.
openeats_web_1 exited with code 0

Thanks.
Jerome CARBEL

**Comment by RyanNoelk** [comment]
Hey there,

That is normal for the web container. It's job is to compile the static content and the nginx server that comes with OpenEats will then server it.

Are you having issues running OpenEats? if so can you please provide some more information as to what is going wrong?

Thanks,
Ryan

**Comment by SirTerrific** [comment]
Hello, thank you for the response. I did not understand the usefulness of the docker web. I put a pause on my project. If I have some issues I'll post them.
