### ISSUE TITLE
Issue Running Openeats

### ISSUE THREAD

**Issue by intrinsicaly** [open-eats/OpenEats#60]
Hi, I am having trouble getting openeats fully running. I have tried running Openeats in both the docker version and the non-docker version as described in the doc's. I have been using virtualbox as a play ground to try and get things going but with limited success. It seems that I can get the site running so that I can see the front page. I can access the admin area. I can add users through the admin area but I can't login as those user on the front page. I have also added news and recipes to the site through the admin area but when I go to the main page the recipes don't show and when I click browse for recipes I get a spinning wheel that doesn't stop and I don't get any recipes. I currently have the docker version up with the following env_prod.list settings

# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=sdfsadfas32e98zsdvhhsnz6udvbksjdhfi4galshjfg
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=True
ALLOWED_HOST=localhost
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=development
NODE_URL=localhost:8080
NODE_API_URL=http://localhost:8080
NODE_LOCALE=en

If I make a change to the env_prod.list I use ./quickstart.py to reload the settings (not sure if that is the correct way or not as none of the changes seems to have made much difference). 
I do get the following which may indicate an issue but I am not sure

Starting OpenEats
==================
Taking a database backup (saving as openeats.sql)...
Error: No such container: openeats_db_1
Taking a image backup save to 'site-media'...
Error: No such container:path: openeats_api_1:/code/site-media/
Stopping openeats_nginx_1_a87702cb3bc1 ... done
Stopping openeats_api_1_3cf1458e940e ... done
Recreating openeats_db_1_51c151ec08fc ... done
Recreating openeats_api_1_3cf1458e940e ... done
Recreating openeats_web_1_b838822f58f5 ... done
Recreating openeats_nginx_1_a87702cb3bc1 ... done
App started. Please wait ~30 seconds for the containers to come online.

Any help would be great.

Cheers

**Comment by RyanNoelk** [comment]
Hey there,

Sorry to see you are having issues. 

Your config looks ok to me and if you are able to see the admin page and the ui then there must be an issue with the ui calling the api.

I'll need a bit more info from you. When you are loading the ui, can you also open your network tab in the debug console. 

After that try clicking around the site and send me the errors or warnings that show up in the network tab.

Thanks!

**Comment by intrinsicaly** [comment]
Sorry for the delay in responding, has been a busy day. 
I was responding with some info as requested when I noticed issue 61 is the same issue I was having. After adjusting the env settings everything started working as expected. Thanks for your time and product.

Cheers

**Comment by RyanNoelk** [comment]
:+1:
