### ISSUE TITLE
Feature Request: Multilanguage

### ISSUE THREAD

**Issue by 8ear** [open-eats/OpenEats#62]
Hi,
is it possible to add multilanguage support per recipe?

Perhaps with a button where you can switch the language in the admin interface you can then create texts and ingedients in various languages. Ingredients should be only defined once per language.

Thanks!!

Kind regards

**Comment by RyanNoelk** [comment]
Hmm, I don't see this as a feature I would work on any time soon. Pull requests welcome tho :)

**Comment by RyanNoelk** [comment]
Closing for now. If someone whats to implement this please reopen or create a PR.
