### ISSUE TITLE
Start up

### ISSUE THREAD

**Issue by zocken1** [open-eats/OpenEats#64]
I am having a few issues getting the app to work:

1: Cannot connect on 80, the nginx settings are 8000:80
2. Can connect on 8000 but when I do none of the links seem to function (cannot log in, when I click browse it just spins)

**Comment by RyanNoelk** [comment]
Hey,

Can you please take a look at this thread and see if that fixes you problems: https://github.com/open-eats/OpenEats/issues/61

-Ryan

**Comment by RyanNoelk** [comment]
Did the issue above help you or are you still having issues?

If you are still having issues can you please provide some more details on your setup?

**Comment by zocken1** [comment]
Sorry I got side tracked and haven't had much chance to work on it.  I tried changing some settings and got it completely borked so tomorrow I am going to try re installing from scratch.

My setup is internet>firewall>nginx reverse proxy server>openeats server the firewall forwards all requests to mydomain.com to nginx which forwards recipes.mydomain.com to the openeats server

**Comment by cearum** [comment]
I had a similar issue doing the same thing, but I don't remember how I fixed it. I'm at work not, but if I remember tonight, I can try to take a look at both my Open Eats config and my NGINX config.

**Comment by cearum** [comment]
So I have this in my env_prod.list:


```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD={passwd}

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY={secret key}
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=recipes.{domain}.net
HTTP_X_FORWARDED_PROTO=True

# Node config
NODE_ENV=production
NODE_URL=localhost:8000
NODE_PORT=8000
ALLOWED_HOST=recipes.{domain}.net
NODE_API_URL=https://recipes.{domain}.net
```
And I have this in my NGINX default config file. Of course I have https enabled (which you should too). I found I had to forward each part for it to work. After that everything was a breeze. 

```
server {    
	listen 443 ssl;

	root /config/www;
	index index.html index.htm index.php;

	server_name  recipes.{domain}.net;

	include /config/nginx/ssl.conf;

	client_max_body_size 0;

    # pass requests for dynamic content
      location / {
          proxy_set_header        Host $host;
          #proxy_set_header        X-Real-IP $remote_addr;
          #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header 		X-Forwarded-Proto https;
	  	  #proxy_ssl_verify		off;
          proxy_pass http://{local-ip-address}:8000;
      }
	
	location /api/ {
		proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header 		X-Forwarded-Proto https;
		#proxy_ssl_verify		off;
	    proxy_pass http://{local-ip-address}:8000/api/;
	}
	
	location /static/ {
		proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header 		X-Forwarded-Proto https;
		#proxy_ssl_verify		off;
		proxy_pass http://{local-ip-address}:8000/static/;
	}
	
	location /admin/ {
		proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header 		X-Forwarded-Proto https;
		#proxy_ssl_verify		off;
		proxy_pass http://{local-ip-address}:8000/admin/;
	}
	
	location /static-files/ {
		proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header 		X-Forwarded-Proto https;
		#proxy_ssl_verify		off;
		proxy_pass http://{local-ip-address}:8000/static-files/;
	}
	
	location /site-media/ {
		proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header 		X-Forwarded-Proto https;
		#proxy_ssl_verify		off;
		proxy_pass http://{local-ip-address}:8000/site-media/;
	}
	
}
```

I hope this helps!

**Comment by Peyje** [comment]
I actually did have the exact same issue. By only changing the API_PORT to 80 in the env_prod.list and the nginx ports to 80:80 in docker-prod.override.yml and restarting the docker containers I got it to work.

**Comment by RyanNoelk** [comment]
Everyone's setup is going to be a little different. I'm glad you all were able to get it working :)
