### ISSUE TITLE
Force login #enhancement #feature request

### ISSUE THREAD

**Issue by intrinsicaly** [open-eats/OpenEats#65]
Is there a way to force a login before any user can browse the site?
Looking at django related info it would appear that this can be achieved by placing some code on each part of the site to check if the user is logged in and redirect to the login page if not. This way the site could be made private.
Is there an easier solution to this? 
Would this be a useful enhancement to be able to switch on/off as required?

Cheers

**Comment by RyanNoelk** [comment]
ATM this is not possible. There is however, there is a way to mark a recipe as private (only allowing people that are logged in to view the recipe).

Adding some type of private mode so that only people that log in can view the site should be possible, but I don't have the time ATM to implement. If you are willing to dig into the code and create a PR, I would be happy to give directions. 

-Ryan

**Comment by intrinsicaly** [comment]
This is probably above my abilities but I can give it a go. I would appreciate any help/direction that you can give me. I appreciate all the effort you have put into this project. Cheers

**Comment by intrinsicaly** [comment]
Hi Ryan, I believe that I have found an elegant way to achieve this feature. It requires a middleware which will redirect all non-logged in users to the login page. Will look into making this work. Will let you know more if I can get it working or need further assistance.  Cheers

**Comment by RyanNoelk** [comment]
Going to close this issue for now.

Since there is an ability to make all recipes private, the only thing this feature would do would redirect users to the login screen. If you really want a private mode you can also just host on an Intranet

**Comment by intrinsicaly** [comment]
Hi Ryan, It took me a while but I eventually got back to this and tried to get the force login to work. I partially had this working with a middleware but I believe that it was then falling over on the react side which wasn't redirecting. I don't have enough knowledge to continue this at the moment but I thought I would let you know anyway and to see if you had any thoughts on this?

Thanks for keeping up the good work.

Cheers

**Comment by RyanNoelk** [comment]
Feel free to share what you have. I can't promise I will get to it in the near future, but other might be interested :)
