### ISSUE TITLE
Far future feature request: federated recipe search

### ISSUE THREAD

**Issue by MattiP451** [open-eats/OpenEats#66]
Just an idea I was toying with, it would be great if you could choose to also search other people's databases when you search for a recipe. Preferably this should be an opt in option so every admin can chose to turn this feature on. Might also need some sort of black list function to filter out instances you don't want to search.

**Comment by RyanNoelk** [comment]
Interesting idea. I don't think I would allow other people DB's to be searched directly. But I think it would be useful to have some sort of huge json file (or collection of json files) hosted here on github that people could import/export.

The demo site might me a place where these recipes can be queried and then some type of import option there to add the recipe to your own site.

**Comment by RyanNoelk** [comment]
Going to close this as I don't see it ever being implemented. If someone wants to implement this, please reopen and we can discuss that it should/should't be
