### ISSUE TITLE
Access Denied SQL error in stock docker deployment

### ISSUE THREAD

**Issue by chetwisniewski** [open-eats/OpenEats#68]
I used the stock recommendations in the repo and get a SQL error when I try to run manage.py createsuperuser.

django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.4' (using password: YES)") 

env_prod.list below:

# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=sdfsadfas32e98zsdvhhsnz6udvbksjdhfi4galshjfg
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=localhost
HTTP_X_FORWARDED_PROTO=false

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_API_URL=http://localhost
NODE_LOCALE=en

**Comment by RyanNoelk** [comment]
Are you runing this script? 
```docker-compose -f docker-prod.yml run --rm --entrypoint 'python manage.py createsuperuser' api```

If so, are you running it from the same machine that you are running OpenEats from?

Another thing to check is to see if your database is accepting any connections.

**Comment by RyanNoelk** [comment]
Please reopen this if you are still having issues
