### ISSUE TITLE
Compose file is invalid

### ISSUE THREAD

**Issue by shadow11001** [open-eats/OpenEats#72]
Adding a remote db, getting an error when using quick-start

ERROR: The Compose file is invalid because:
Service db has neither an image nor a build context specified. At least one must be provided.

Added the info of my db to env_prod.list

Full Output:

==================
Starting OpenEats
==================
Using remote DB...
ERROR: The Compose file is invalid because:
Service db has neither an image nor a build context specified. At least one must be provided.
ERROR: The Compose file is invalid because:
Service db has neither an image nor a build context specified. At least one must be provided.
ERROR: The Compose file is invalid because:
Service db has neither an image nor a build context specified. At least one must be provided.
ERROR: The Compose file is invalid because:
Service db has neither an image nor a build context specified. At least one must be provided.
App started. Please wait ~30 seconds for the containers to come online.

**Comment by RyanNoelk** [comment]
Looks like you still have some reference to the db in your docker compose file.

I'm thinking the issue is due to some new config code I added recently (on my phone atm so cant check well)

Can you confirm that you dont have any refernece to the db in your docker-compose.yml file?

**Comment by RyanNoelk** [comment]
Since I recently updated the override file to include the DB changes then you will need to remove the code from there as well.

See: https://github.com/open-eats/OpenEats/blob/master/docs/samples/sample_docker_prod_override.yml

You'll want it to look like:
```
version: '2.3'
services:
  nginx:
    ports:
      - "8000:80"
    restart: always
  api:
    restart: always
  web:
    restart: on-failure
```

**Comment by RyanNoelk** [comment]
I hope the above helped you. Please reopen if you are still having issues.
