### ISSUE TITLE
Working on 8000 but not 80

### ISSUE THREAD

**Issue by iinux101** [open-eats/OpenEats#73]
Hey all, First and foremost, I just want to say thank you for this awesome application! I know this is entirely my fault, but just wanting to see how I go about changing it to listen on port 80 instead of 8000.

Bellow is my config : 
anything in () is my own stuff.

# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=(PASSWORD)

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=(SECRET_KEY)
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=localhost,(DOMAIN.COM)
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_API_URL=http://(DOMAIN.COM):8000
NODE_LOCALE=en

**Comment by iinux101** [comment]
Doh! Got it : 
cp docs/samples/sample_docker_prod_override.yml docker-prod.override.yml

Forgot about that file >_<

Thanks, now to figure out how to set up SSL....

**Comment by RyanNoelk** [comment]
Glad you got it figured out. Let me know fi you have any other issues :)

**Comment by iinux101** [comment]
is there any documentation or rough a rough guide for setting up SSL with lets encrypt?

**Comment by RyanNoelk** [comment]
https://github.com/open-eats/OpenEats/blob/master/docs/Creating_a_proxy_server_for_docker.md

https://github.com/open-eats/OpenEats/blob/master/docs/samples/sample_nginx_proxy

That's the docs I have for creating a proxy server with nginx. I leave serving the App with SSL up to the end user. I you are looking for something super simple https://certbot.eff.org/ is a good choose

**Comment by iinux101** [comment]
I guess I am just a little lost with all of it since I've truly never worked with docker. 
I currently have my site set up running on just port 80, so my docker-prod.override.yml is set up as follows : 
```
  nginx:
    ports:
      - "80:80"
```

Should I change this to : 
```
  nginx:
    ports:
      - "80:80"
      - "443:443"
```

Would I just need to log into the web container and set it up to force redirect to SSL? And then install certbot outside of docker?
