### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by agenttwelve** [open-eats/OpenEats#75]
Hello, I have just got the site up and running, but I am having an issue where I cannot upload an image. Upon doing so, I get a "Photo failed to save! Please try again." error. 

I checked the web browser console and got this result "VM301:1 PATCH http://domain.com/api/v1/recipe/recipes/quinoa-skillet-2/ 413 (Request Entity Too Large)". 

From the API logs, "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField Recipe.pub_date received a naive datetime (2018-12-05 00:00:00) while time zone support is active."

**Comment by agenttwelve** [comment]
Seems to be due to image size. I have closed this issue.

**Comment by RyanNoelk** [comment]
The issue here is that the image is just too large. You can use a random web tool to reduce the size and still maintain the quality (https://www.reduceimages.com/)
