### ISSUE TITLE
Comments/Ratings

### ISSUE THREAD

**Issue by agenttwelve** [open-eats/OpenEats#76]
Hello,

It seems that I am not able to submit a review on the recipe page. Upon submission the text clears. However, I am able to submit a review from the 'My account' page. Is there something that I am missing?

**Comment by RyanNoelk** [comment]
Look's like I have a bug that if you don't submit a rating **and** a comment the form just get's cleared out without any error message.

Can you make sure that when you submit a comment that you include a rating and a comment and see if that works?

**Comment by agenttwelve** [comment]
I just tried doing a rating and a comment, with the same result.

**Comment by RyanNoelk** [comment]
Do u mind posting the message that you are getting from the API when you try to summit a comment. AKA: opening your dev tools in the browser and posting the results from the API call.

![image](https://user-images.githubusercontent.com/11916338/49542540-3030e280-f8d6-11e8-9277-7df0d122f7fd.png)

**Comment by agenttwelve** [comment]
My apologies for my dumb moment, I did not try on the superuser account. This attempt was from a regular user account. I will need to adjust permissions accordingly.

<img width="880" alt="screen shot 2018-12-05 at 3 41 29 pm" src="https://user-images.githubusercontent.com/40524971/49542931-d532c780-f8a4-11e8-95fd-a0303c8b88fb.png">

However, from the super user account, I am required to have both a review and comment.

**Comment by RyanNoelk** [comment]
Normal accounts should have access to adding a comment. I'll take a look into why normal users can't create comments

**Comment by agenttwelve** [comment]
I did try to manually add permissions for the regular user. That was unsuccessful. I will await your investigation.

**Comment by RyanNoelk** [comment]
There was an issue with the way that permissions where setup that prevented non admin users for creating comments.

I have a fix for this on the latest master. Please check it out and let me know if u have any issues. See here for the update quide: https://github.com/open-eats/OpenEats/blob/master/docs/Updating_the_App.md

**Comment by agenttwelve** [comment]
Works like a charm! Thanks a bunch for your help!
