### ISSUE TITLE
Change API models.py object reference

### ISSUE THREAD

**Issue by mbryantms** [open-eats/OpenEats#81]
The Django admin section of the API does not display objects with their name appropriately. Instead it refers to each as the model name with a successive number in parentheses. We should be able to fix this using a simple change, refer to Django docs: https://docs.djangoproject.com/en/2.1/ref/models/instances/#str

Currently the models include:

`def __unicode__(self):
    return '%s' % self.title
`

And instead I think it should be:

`def __str__(self):
    return '%s' % self.title`

Thoughts?

**Comment by RyanNoelk** [comment]
You're right! PR is welcome.

**Comment by RyanNoelk** [comment]
Fixed in: https://github.com/open-eats/openeats-api/pull/21
