### ISSUE TITLE
OpenEats not logging in

### ISSUE THREAD

**Issue by jeffest-jeff** [open-eats/OpenEats#82]
I can't log in to OpenEats web. I've created a superuser with the script, but it won't go any further than that. I enter the user and password I created into OpenEats web and click Sign In and nothing happens.
What am I missing?

**Comment by RyanNoelk** [comment]
Sorry to see you are having issues.

Can you try logging into the admin panel in a new private window (your.domain.com/admin). If that works for you can you open up your console and send me the errors you are getting when trying to login via the GUI.

**Comment by jeffest-jeff** [comment]
The admin panel wasn't working yesterday, but now it's working since I
redeployed the containers after changing ALLOWED_HOST to * in the
env_prod.list.

This is the error I get from the Firefox Web Console when I try to login.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
remote resource at http://localhost:8080/api/v1/accounts/obtain-auth-token/.
(Reason: CORS request did not succeed).[Learn More]

I noticed that the API address in env_prod.list is still set to localhost,
but the API container is separate. So I changed the API addresses in the
env_prod.list file and removed/redeployed. No luck. Same error.



*Jeff Kleinhenz*

**Comment by jeffest-jeff** [comment]
I've also noticed that openeats_web1 keeps dying and stopping itself. But
if I start the openeats_web1 container, it prevents me from getting to the
openeats page. Only after shutting down openeats_web1 does it let me get
back to that page.

*Jeff Kleinhenz*

**Comment by RyanNoelk** [comment]
If you are using localhost as your domain you need to make sure that you are serving the API and the UI from the same domain and port. So if you want to view OpenEats from localhost:8080 that is the thing you need to add to the allowed_hosts. 

There currently are some issues with severing the app via localhost that I haven't gotten around to looking at. I would recommend that you use a domain name to server the app. See: https://github.com/open-eats/OpenEats/issues/61

You can use chrome plugin to disable CORS for OpenEats if you like: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

`openeats_web` is suppose to stop. it's job is to generate the static content (js/css/html) that the nginx server will serve. It generates this content based on the `env_prod.list` file. So if you can view the UI then it's working.

**Comment by inktrap** [comment]
I have the same issue and I tried various values for api url and allowed hosts.
Could you update the documentation with a section how to run openeats from localhost with a complete, working config? Does this work for [running the app with docker for dev](https://github.com/open-eats/OpenEats/blob/master/docs/Running_the_App_in_dev.md#running-the-app-with-docker-for-development)?

Also, this line: ``docker-compose run --rm api bash``should use ``sh`` not ``bash`` (there was an issue for that but someone forgot to change the docs).

**Comment by RyanNoelk** [comment]
If you are just looking to run the app locally then you can run it in dev mode. This does have some security risks and small perform loss. But it's not a huge issue and will get you up and running quickly.

See: https://github.com/open-eats/OpenEats/blob/master/docs/Running_the_App_in_dev.md

Not that this will use the following ports:
- 8080: for the web app
- 8000: for the API
- 3306: for the mysql DB

I'm going to work on some better documentation in the next few weeks, I'll been busy with my day job :P

**Comment by RyanNoelk** [comment]
For running OpenEats via LAN please see: https://github.com/open-eats/OpenEats/issues/61
