### ISSUE TITLE
Can't save images

### ISSUE THREAD

**Issue by septem9er** [open-eats/OpenEats#84]
I get an error when I try to save an image for a recipe, which says I should try it again. The recipe saves anyway. I do not see any error in the logs of the 4 docket containers, sceptre of a lot of errors in the db container stating that there were failed login attemps. I am running openeats behind Bronx as a reverse proxy.

**Comment by RyanNoelk** [comment]
Sorry to here that. What is the type and size of the images you are try to
import? (For example: png 10mbits)

OpenEats has some limits on the size of images you can save. Iirc its 10
megabytes (I'll double check this)

**Comment by septem9er** [comment]
Thanks for your fast reply. Its a jpg and its size is 5,7 MB.

**Comment by septem9er** [comment]
Also, I just noticed that when I open an recipe there is no print button and the placeholder image is not beeing displayed. In the overview of recipes, the placeholder image is getting displayed.

**Comment by RyanNoelk** [comment]
Can you add the image you are trying to upload to github as well as adding
the error message the API is senind back?
You can get the error via chrome dev tools in the network tab.

**Comment by septem9er** [comment]
It does not matter which photo I use, as long as I took it with my phone camera, but some other photos worked. I attached you a sample picture.

The API send the error 413, so it seems the picture is to large?

Also, I noticed that I get the following error as well:
`Refused to create a worker from 'https://openeats.lindemann.space/service-worker.js' because it violates the following Content Security Policy directive: "worker-src 'none'".`

The nginx which I use as reverse proxy, does not set this header. At least it is not in my config. Does the one bundled to openeats does it?


![img_20190114_172313](https://user-images.githubusercontent.com/33379902/51125978-3d6cb580-1822-11e9-8335-149f0862ea6c.jpg)

**Comment by RyanNoelk** [comment]
Yep, the sever is rejecting the image because it is too large. I haven't had a chance to check the max image upload size. So can you try with something smaller than 500kB?

Not sure why the app is not allowing service workers. It works fine for me. TBH the service worker isn't a huge deal not to have working. It's just a small cache for the UI.

**Comment by RyanNoelk** [comment]
I added a note to the Recipe creation page that all recipe images need to be less than 500kB.
