### ISSUE TITLE
Recipe Links cause 500 Internal Server Error

### ISSUE THREAD

**Issue by Jzooor** [open-eats/OpenEats#86]
I am trying to use recipe links on some of my recipes. Correct me if I am wrong, but I am assuming that the recipe links field is how you get other recipes as part of the ingredients. For example, on https://open-eats.github.io/recipe/1 the "Tasty Chili 2" shows up as a clickable link in the ingredients.

In the recipe links field, I can get the list of recipes by typing a ':' as the tool tip suggests. And the preview looks reasonable, though the link address in the preview shows up pointing to "https://<mydomain>/recipe/undefined".

When I try to save with anything in the recipe links field the recipe fails to save. Banner shows up at the top saying "Saving recipe. Please wait..." and it stays on the recipe edit page.
In Chrome's console after clicking save I get...
```
PATCH https://<mydomain>/api/v1/recipe/recipes/reeses-pudding-parfait/ 500 (Internal Server Error)
(anonymous) @ client.js:772
(anonymous) @ client.js:676
(anonymous) @ request-base.js:238
(anonymous) @ request-base.js:237
(anonymous) @ RecipeFormActions.js:96
(anonymous) @ index.js:8
(anonymous) @ bindActionCreators.js:3
(anonymous) @ RecipeForm.js:34
b @ react-dom.production.min.js:36
invokeGuardedCallback @ react-dom.production.min.js:35
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:35
v @ react-dom.production.min.js:36
executeDispatchesInOrder @ react-dom.production.min.js:38
S @ react-dom.production.min.js:46
T @ react-dom.production.min.js:46
k @ react-dom.production.min.js:46
processEventQueue @ react-dom.production.min.js:49
handleTopLevel @ react-dom.production.min.js:57
x @ react-dom.production.min.js:43
batchedUpdates @ react-dom.production.min.js:190
O @ react-dom.production.min.js:41
E @ react-dom.production.min.js:41
batchedUpdates @ react-dom.production.min.js:42
dispatchEvent @ react-dom.production.min.js:45
```

**Comment by RyanNoelk** [comment]
That is strange. I will take a deep look into this on the next few days.

Thanks for reporting!

**Comment by RyanNoelk** [comment]
Hey there. Sorry for the long delay. I ave a fix for the sub recipe issue that you reported.
- https://github.com/open-eats/openeats-web/pull/27
- https://github.com/open-eats/openeats-api/pull/24

I'll be merging them today :)

**Comment by RyanNoelk** [comment]
This should be solved now.
