### ISSUE TITLE
News page not accessible for anonymous

### ISSUE THREAD

**Issue by arnonh** [open-eats/OpenEats#89]
After the last update 1.5 (pulling from docker hub)
The news page is no longer accessible without logging in
only the browse and recipe pages are accessible 

And thank you for this amazing project!

**Comment by RyanNoelk** [comment]
Doh! Thanks for the heads up. I'll have an update today or tomorrow with a
fix.

**Comment by RyanNoelk** [comment]
This should be resolved now (Release 1.5.1). Please reopen this if you are still having an issue. 

Note: Please give docker hub about an hour to build the new images.
