### ISSUE TITLE
Image links are incorrect

### ISSUE THREAD

**Issue by ghost** [open-eats/OpenEats#90]
Please forgive me if I have done something wrong in setting up the project, I have done my best to figure this out.  I followed the setup guide and got the docker containers running; I use apache as a webserver and am proxying a subdomain to the docker project.  Everything works, except uploaded images.  They upload okay, but on the webpage the image URLs are to http://localhost:7000/<IMAGEURL> instead of https://openeats.properdomain/<IMAGEURL>.  This is only happening for the user-uploaded images of recipes.

I'm attaching my env_prod.list to show how I configured the docker container in case that helps.
```# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=secret
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=localhost
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8044
NODE_PORT=8044
NODE_API_URL=https://openeats.domain.house/
NODE_LOCALE=en
```

**Comment by RyanNoelk** [comment]
This defiantly has something to do with how the Apache server and OpenEats are talking with each other. The OpenEats API needs to know the hostname that it is being called from, ifthe request was https or http, etc... It gets this info from the request. So if your Apache server isn't sending the complete URL with the request then that will cause a problem when generating links.

I'm no expect on Apache, but will look into it. For reference, this is how it's done with nginx: https://github.com/open-eats/OpenEats/blob/master/docs/samples/sample_nginx_proxy


For some insight into the code (if you are interested). The URL for the image is build here:
- https://github.com/open-eats/openeats-api/blob/master/v1/recipe/serializers.py#L32
- https://docs.djangoproject.com/en/2.1/ref/request-response/#django.http.HttpRequest.build_absolute_uri

**Comment by RyanNoelk** [comment]
Did some quick googling. Can you try this:
- https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#ProxyPreserveHost
- https://serverfault.com/questions/557233/apache-proxy-http-redirect-to-ip-and-set-hostname

**Comment by ghost** [comment]
Thanks for the help and the insight on what was going on.   Setting ProxyPreserveHost to On and changing my ALLOWED_HOST to the proper domain (since it now believes the requests are coming from the domain and not from localhost) has it generating links that seem to be mostly correct - the only issue now is that the links that are being generated are http and not https - maybe because the request to the OpenEats API is via http and not https?

In any case I'll keep poking at my Apache setup and figure it out on that end.

**Comment by RyanNoelk** [comment]
I believe the https issue is caused by this: https://docs.djangoproject.com/en/1.11/ref/settings/#secure-proxy-ssl-header.

You have the settings correct by setting: `HTTP_X_FORWARDED_PROTO=true`.

You'll also need to make sure ur passing that header in ur Apache settings. Maybe something like this:
https://webmasters.stackexchange.com/questions/97005/setting-x-forwarded-proto-under-apache-2-4

**Comment by ghost** [comment]
That did the trick.  Thank you again for taking the time.

**Comment by RyanNoelk** [comment]
Would you mind posting an example of the Apache config you are using so others may use it?

**Comment by ghost** [comment]
Not at all.  I have created a file in sites-available with these contents:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName openeats.domain.house

    # This passes all connections to this subdomain to the docker
    # container for OpenEats
    ProxyPreserveHost On

    ProxyPass / http://localhost:7000/

    # Maintain an SSL connection in headers to the docker container
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
</VirtualHost>
</IfModule>
```

combined with an env_prod.list of 

```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=secretkey
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=openeats.domain.house
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8044
NODE_PORT=8044
NODE_API_URL=https://openeats.domain.house/
NODE_LOCALE=en
```

Enabling the site above  (along with using lets-encrypt to generate a SSL cert for apache) has it all up and running.
