### ISSUE TITLE
OpenEats on a subdirectory behind a reverse-proxy

### ISSUE THREAD

**Issue by jnikolich** [open-eats/OpenEats#91]
1. OpenEats is wonderful!  Thank you very much for it.

I'm attempting to run OpenEats behind an apache reverse-proxy in order to support SSL-only connections.  I think I'm mostly there, however the issue I'm having is that my Apache reverse-proxy uses subdirectories to differenciate between various websites I host.  e.g. https://www.example.com/openeats is my openeats instance, while https://www.example.com/superblah is my superblah site.

For reference, OpenEats runs on my docker host (docker.example.com), while my Apache reverse-proxy runs on my webhost (www.example.com).

I have a config stanza similiar to the following in my apache config:
 ```apache
<Location /openeats/>
        ProxyPreserveHost    On
        ProxyPass            "http://docker.example.com:8000/openeats/"
        ProxyPassReverse     "http://docker.example.com:8000/openeats/"
        RequestHeader        set X-Forwarded-Proto   expr=%{REQUEST_SCHEME}
        RequestHeader        set X-Forwarded-SSL     expr=%{HTTPS}
  </Location>
```

(**_BTW_** _The Proxy directives appear within a _**Location**_ stanza, thus they do not take their originating URL from a 1st arg.  Instead, you omit that arg and they take their originating URL from the Location tag itself_.)

This does seem to work WRT the original request.  Sort of.  However the redirects (I think that's what they are) coming back from the OpenEats docker instance are lacking the "openeats/" subdirectory piece of the URL.  They appear to be hardcoded to use "/", as illustrated by the following excerpt from my Apache log:
```
192.168.240.120 - - [14/May/2019:12:33:11 -0400] "GET /openeats/ HTTP/1.1" 200 865 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
192.168.240.120 - - [14/May/2019:12:33:11 -0400] "GET /static/css/main.5db71e20.css HTTP/1.1" 404 226 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
192.168.240.120 - - [14/May/2019:12:33:11 -0400] "GET /static/js/main.163c8ad2.js HTTP/1.1" 404 224 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
192.168.240.120 - - [14/May/2019:12:33:11 -0400] "GET /images/favicon.ico HTTP/1.1" 404 216 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
```
The initial request is successfull (**200**), while the remainder error out (**_404_**).

This will all probably just start working wonderfully if I can reconfigure OpenEats to get served off a URL based on "**/openeats/**" instead of "**/**".  However I cannot for-the-life-of me figure out how to successfully configure that in the OpenEats config files.  I have tried the following variants within _**env_prod.list**_:
```config
NODE_API_URL=http://192.168.240.113:8000
NODE_API_URL=http://192.168.240.113:8000/
NODE_API_URL=http://docker.example.com:8000/openeats
NODE_API_URL=http://docker.example.com:8000/openeats/
```
... However I suspect that is not the proper place to make this change.  Any advice/recommendations would be greatly appreciated!

Thanks again

**Comment by RyanNoelk** [comment]
Hmm. I'll have to do some digging to see if this is possible. I'm by no means a network expert so not sure how much help I will be :/

There is a proxy nginx server in the docker instance that is directly the traffic to the different containers. The config is here: https://github.com/open-eats/openeats-nginx/blob/master/default.conf

You can play around with that to make it do what you want.
