### ISSUE TITLE
Question: Option to say logged in

### ISSUE THREAD

**Issue by Don-Swanson** [open-eats/OpenEats#95]
Hello, is there a way to stay logged in after logging in? This will be primarily used on a tablet in the kitchen and would like to be able to stay logged in so we can use it as a grocery list too. (unless there is a way to make the grocery list public and editable by the public)

**Comment by RyanNoelk** [comment]
By default you should stay logged in. When I use Chrome on Mac, PC, Linux, and Android I stay logged in.

OpenEats used local storage to keep you logged in. Could you give me some more info on the browsers/OS you are having the issue with.

**Comment by Don-Swanson** [comment]
Ah, you are correct. My wife was complaining about it not staying logged in on her iPad, but it appears to stay logged in if I switch her to the Firefox browser (as well as all other devices in the house.)
Thanks
