### ISSUE TITLE
Problems installing on Ubuntu Server with nginx

### ISSUE THREAD

**Issue by mourningsun75** [open-eats/OpenEats#98]
Just installed as described here:

https://github.com/open-eats/OpenEats/blob/master/docs/Running_the_App_Without_Docker.md 

Taken the nginx Config from here
https://github.com/open-eats/openeats-nginx/blob/master/default.conf#L38

No errors. But when i open the url nothing happens. Only the cook icon and page title on the tab are shown.

Here is my config:
`
upstream api {
  ip_hash;
  server api:5210;
}

server {

   listen       443 ssl;
   include /etc/nginx/snippets/ssl.conf;
   include /etc/nginx/snippets/ssl-params.conf;

    #listen 80;
    server_name openeats.bunkertor.org;

    location / {
        root /opt/openeats/openeats-nginx/public-ui;
        try_files $uri $uri/ /index.html;
    }

    location /static/  {
        root /opt/openeats/openeats-nginx/public-ui;
        gzip on;
        gzip_types text/plain text/xml text/css
            text/comma-separated-values
            text/javascript application/x-javascript
            application/javascript
            application/atom+xml;

        expires max;
    }

    location /api/ {
        proxy_pass http://api;
        proxy_set_header Host $http_host;
    }

    location /admin/ {
        proxy_pass http://api;
        proxy_set_header Host $http_host;
    }

    location /static-files/ {
        root /opt/openeats/openeats-nginx/static-files;
        try_files $uri /static-files/$uri;
    }

    location /site-media/ {
        root /opt/openeats/openeats-nginx/site-media;
        try_files $uri /site-media/$uri;
    }
}
`

Could someone please help me?

**Comment by mourningsun75** [comment]
Nobody can Help?
No Docker, nginx and Ubuntu Server

**Comment by JasonSanDiego** [comment]
I haven't installed via this method, but have you checked the Chrome console for errors?

**Comment by mourningsun75** [comment]
Yes, here is the error:

```
index.js:35 Uncaught ReferenceError: process is not defined
    at Object.<anonymous> (index.js:35)
    at t (bootstrap 9ce35404300a1dd9ec6c:19)
    at Object.<anonymous> (main.ecf71638.js:28807)
    at t (bootstrap 9ce35404300a1dd9ec6c:19)
    at bootstrap 9ce35404300a1dd9ec6c:62
    at bootstrap 9ce35404300a1dd9ec6c:62
```

**Comment by JasonSanDiego** [comment]
Sorry, I'm not able to help. Some Googling suggests it has something to do with the webpack, so clearly something isn't deployed correctly, but that's about all I'm able to gather, as I'm not familiar with Node/JS at this level.

**Comment by felinira** [comment]
I had the same issue and solved it. You have probably missed this line:
`. .env`
If you don't source the environment you will get this error. The error is very misleading though.
